export enum LocationType {
  WisdomBoardSpot = 1,
  KitsunePawnSpotOnWisdomBoard,
  PowerTokenSpotOnWisdomBoard,
  KitsuCardDeckSpotOnWisdomBoard,
  KitsuCardDiscardSpotOnWisdomBoard,
  DiscardedPowerTokenAreaOnWisdomBoard,
  SetupCardSpot,
  ClanCardSpot,
  LeaderTokenSpotOnClanCard,
  PowerTokenSpotOnClanCard,
  PowerTokenSpotOnKitsuCard,
  PlayerHand,
  PlayedKitsuCardSpot,
  VictoryCardsSpot,
  DiscardedCardsToPickSpot,
}
